/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ynthm.avro.cf88_trex.cf_app_startlog;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Value extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6541663863367566805L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Value\",\"namespace\":\"com.ynthm.avro.cf88_trex.cf_app_startlog\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"package_name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"version\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"deviceType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"source\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"media\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"brand_series\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"brand_word\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"key_word\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"ip\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"imei\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"oaid\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"create_time\",\"type\":[\"null\",\"long\"],\"default\":null}],\"connect.name\":\"com.ynthm.avro.cf88_trex.cf_app_startlog.Value\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Value> ENCODER =
      new BinaryMessageEncoder<Value>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Value> DECODER =
      new BinaryMessageDecoder<Value>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Value> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Value> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Value> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Value>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Value to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Value from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Value instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Value fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int id;
   private java.lang.CharSequence package_name;
   private java.lang.CharSequence version;
   private java.lang.CharSequence deviceType;
   private java.lang.CharSequence source;
   private java.lang.CharSequence media;
   private java.lang.CharSequence brand_series;
   private java.lang.CharSequence brand_word;
   private java.lang.CharSequence key_word;
   private java.lang.CharSequence ip;
   private java.lang.CharSequence imei;
   private java.lang.CharSequence oaid;
   private java.lang.Long create_time;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Value() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param package_name The new value for package_name
   * @param version The new value for version
   * @param deviceType The new value for deviceType
   * @param source The new value for source
   * @param media The new value for media
   * @param brand_series The new value for brand_series
   * @param brand_word The new value for brand_word
   * @param key_word The new value for key_word
   * @param ip The new value for ip
   * @param imei The new value for imei
   * @param oaid The new value for oaid
   * @param create_time The new value for create_time
   */
  public Value(java.lang.Integer id, java.lang.CharSequence package_name, java.lang.CharSequence version, java.lang.CharSequence deviceType, java.lang.CharSequence source, java.lang.CharSequence media, java.lang.CharSequence brand_series, java.lang.CharSequence brand_word, java.lang.CharSequence key_word, java.lang.CharSequence ip, java.lang.CharSequence imei, java.lang.CharSequence oaid, java.lang.Long create_time) {
    this.id = id;
    this.package_name = package_name;
    this.version = version;
    this.deviceType = deviceType;
    this.source = source;
    this.media = media;
    this.brand_series = brand_series;
    this.brand_word = brand_word;
    this.key_word = key_word;
    this.ip = ip;
    this.imei = imei;
    this.oaid = oaid;
    this.create_time = create_time;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return package_name;
    case 2: return version;
    case 3: return deviceType;
    case 4: return source;
    case 5: return media;
    case 6: return brand_series;
    case 7: return brand_word;
    case 8: return key_word;
    case 9: return ip;
    case 10: return imei;
    case 11: return oaid;
    case 12: return create_time;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: package_name = (java.lang.CharSequence)value$; break;
    case 2: version = (java.lang.CharSequence)value$; break;
    case 3: deviceType = (java.lang.CharSequence)value$; break;
    case 4: source = (java.lang.CharSequence)value$; break;
    case 5: media = (java.lang.CharSequence)value$; break;
    case 6: brand_series = (java.lang.CharSequence)value$; break;
    case 7: brand_word = (java.lang.CharSequence)value$; break;
    case 8: key_word = (java.lang.CharSequence)value$; break;
    case 9: ip = (java.lang.CharSequence)value$; break;
    case 10: imei = (java.lang.CharSequence)value$; break;
    case 11: oaid = (java.lang.CharSequence)value$; break;
    case 12: create_time = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'package_name' field.
   * @return The value of the 'package_name' field.
   */
  public java.lang.CharSequence getPackageName() {
    return package_name;
  }


  /**
   * Sets the value of the 'package_name' field.
   * @param value the value to set.
   */
  public void setPackageName(java.lang.CharSequence value) {
    this.package_name = value;
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public java.lang.CharSequence getVersion() {
    return version;
  }


  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(java.lang.CharSequence value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'deviceType' field.
   * @return The value of the 'deviceType' field.
   */
  public java.lang.CharSequence getDeviceType() {
    return deviceType;
  }


  /**
   * Sets the value of the 'deviceType' field.
   * @param value the value to set.
   */
  public void setDeviceType(java.lang.CharSequence value) {
    this.deviceType = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return The value of the 'source' field.
   */
  public java.lang.CharSequence getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'media' field.
   * @return The value of the 'media' field.
   */
  public java.lang.CharSequence getMedia() {
    return media;
  }


  /**
   * Sets the value of the 'media' field.
   * @param value the value to set.
   */
  public void setMedia(java.lang.CharSequence value) {
    this.media = value;
  }

  /**
   * Gets the value of the 'brand_series' field.
   * @return The value of the 'brand_series' field.
   */
  public java.lang.CharSequence getBrandSeries() {
    return brand_series;
  }


  /**
   * Sets the value of the 'brand_series' field.
   * @param value the value to set.
   */
  public void setBrandSeries(java.lang.CharSequence value) {
    this.brand_series = value;
  }

  /**
   * Gets the value of the 'brand_word' field.
   * @return The value of the 'brand_word' field.
   */
  public java.lang.CharSequence getBrandWord() {
    return brand_word;
  }


  /**
   * Sets the value of the 'brand_word' field.
   * @param value the value to set.
   */
  public void setBrandWord(java.lang.CharSequence value) {
    this.brand_word = value;
  }

  /**
   * Gets the value of the 'key_word' field.
   * @return The value of the 'key_word' field.
   */
  public java.lang.CharSequence getKeyWord() {
    return key_word;
  }


  /**
   * Sets the value of the 'key_word' field.
   * @param value the value to set.
   */
  public void setKeyWord(java.lang.CharSequence value) {
    this.key_word = value;
  }

  /**
   * Gets the value of the 'ip' field.
   * @return The value of the 'ip' field.
   */
  public java.lang.CharSequence getIp() {
    return ip;
  }


  /**
   * Sets the value of the 'ip' field.
   * @param value the value to set.
   */
  public void setIp(java.lang.CharSequence value) {
    this.ip = value;
  }

  /**
   * Gets the value of the 'imei' field.
   * @return The value of the 'imei' field.
   */
  public java.lang.CharSequence getImei() {
    return imei;
  }


  /**
   * Sets the value of the 'imei' field.
   * @param value the value to set.
   */
  public void setImei(java.lang.CharSequence value) {
    this.imei = value;
  }

  /**
   * Gets the value of the 'oaid' field.
   * @return The value of the 'oaid' field.
   */
  public java.lang.CharSequence getOaid() {
    return oaid;
  }


  /**
   * Sets the value of the 'oaid' field.
   * @param value the value to set.
   */
  public void setOaid(java.lang.CharSequence value) {
    this.oaid = value;
  }

  /**
   * Gets the value of the 'create_time' field.
   * @return The value of the 'create_time' field.
   */
  public java.lang.Long getCreateTime() {
    return create_time;
  }


  /**
   * Sets the value of the 'create_time' field.
   * @param value the value to set.
   */
  public void setCreateTime(java.lang.Long value) {
    this.create_time = value;
  }

  /**
   * Creates a new Value RecordBuilder.
   * @return A new Value RecordBuilder
   */
  public static com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder newBuilder() {
    return new com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder();
  }

  /**
   * Creates a new Value RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Value RecordBuilder
   */
  public static com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder newBuilder(com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder other) {
    if (other == null) {
      return new com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder();
    } else {
      return new com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder(other);
    }
  }

  /**
   * Creates a new Value RecordBuilder by copying an existing Value instance.
   * @param other The existing instance to copy.
   * @return A new Value RecordBuilder
   */
  public static com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder newBuilder(com.ynthm.avro.cf88_trex.cf_app_startlog.Value other) {
    if (other == null) {
      return new com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder();
    } else {
      return new com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder(other);
    }
  }

  /**
   * RecordBuilder for Value instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Value>
    implements org.apache.avro.data.RecordBuilder<Value> {

    private int id;
    private java.lang.CharSequence package_name;
    private java.lang.CharSequence version;
    private java.lang.CharSequence deviceType;
    private java.lang.CharSequence source;
    private java.lang.CharSequence media;
    private java.lang.CharSequence brand_series;
    private java.lang.CharSequence brand_word;
    private java.lang.CharSequence key_word;
    private java.lang.CharSequence ip;
    private java.lang.CharSequence imei;
    private java.lang.CharSequence oaid;
    private java.lang.Long create_time;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.package_name)) {
        this.package_name = data().deepCopy(fields()[1].schema(), other.package_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.version)) {
        this.version = data().deepCopy(fields()[2].schema(), other.version);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.deviceType)) {
        this.deviceType = data().deepCopy(fields()[3].schema(), other.deviceType);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.source)) {
        this.source = data().deepCopy(fields()[4].schema(), other.source);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.media)) {
        this.media = data().deepCopy(fields()[5].schema(), other.media);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.brand_series)) {
        this.brand_series = data().deepCopy(fields()[6].schema(), other.brand_series);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.brand_word)) {
        this.brand_word = data().deepCopy(fields()[7].schema(), other.brand_word);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.key_word)) {
        this.key_word = data().deepCopy(fields()[8].schema(), other.key_word);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.ip)) {
        this.ip = data().deepCopy(fields()[9].schema(), other.ip);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.imei)) {
        this.imei = data().deepCopy(fields()[10].schema(), other.imei);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.oaid)) {
        this.oaid = data().deepCopy(fields()[11].schema(), other.oaid);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.create_time)) {
        this.create_time = data().deepCopy(fields()[12].schema(), other.create_time);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
    }

    /**
     * Creates a Builder by copying an existing Value instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ynthm.avro.cf88_trex.cf_app_startlog.Value other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.package_name)) {
        this.package_name = data().deepCopy(fields()[1].schema(), other.package_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.version)) {
        this.version = data().deepCopy(fields()[2].schema(), other.version);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.deviceType)) {
        this.deviceType = data().deepCopy(fields()[3].schema(), other.deviceType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.source)) {
        this.source = data().deepCopy(fields()[4].schema(), other.source);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.media)) {
        this.media = data().deepCopy(fields()[5].schema(), other.media);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.brand_series)) {
        this.brand_series = data().deepCopy(fields()[6].schema(), other.brand_series);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.brand_word)) {
        this.brand_word = data().deepCopy(fields()[7].schema(), other.brand_word);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.key_word)) {
        this.key_word = data().deepCopy(fields()[8].schema(), other.key_word);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.ip)) {
        this.ip = data().deepCopy(fields()[9].schema(), other.ip);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.imei)) {
        this.imei = data().deepCopy(fields()[10].schema(), other.imei);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.oaid)) {
        this.oaid = data().deepCopy(fields()[11].schema(), other.oaid);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.create_time)) {
        this.create_time = data().deepCopy(fields()[12].schema(), other.create_time);
        fieldSetFlags()[12] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'package_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getPackageName() {
      return package_name;
    }


    /**
      * Sets the value of the 'package_name' field.
      * @param value The value of 'package_name'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setPackageName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.package_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'package_name' field has been set.
      * @return True if the 'package_name' field has been set, false otherwise.
      */
    public boolean hasPackageName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'package_name' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearPackageName() {
      package_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public java.lang.CharSequence getVersion() {
      return version;
    }


    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setVersion(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.version = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearVersion() {
      version = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'deviceType' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeviceType() {
      return deviceType;
    }


    /**
      * Sets the value of the 'deviceType' field.
      * @param value The value of 'deviceType'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setDeviceType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.deviceType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceType' field has been set.
      * @return True if the 'deviceType' field has been set, false otherwise.
      */
    public boolean hasDeviceType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'deviceType' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearDeviceType() {
      deviceType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * @return The value.
      */
    public java.lang.CharSequence getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * @param value The value of 'source'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.source = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'source' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearSource() {
      source = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'media' field.
      * @return The value.
      */
    public java.lang.CharSequence getMedia() {
      return media;
    }


    /**
      * Sets the value of the 'media' field.
      * @param value The value of 'media'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setMedia(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.media = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'media' field has been set.
      * @return True if the 'media' field has been set, false otherwise.
      */
    public boolean hasMedia() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'media' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearMedia() {
      media = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'brand_series' field.
      * @return The value.
      */
    public java.lang.CharSequence getBrandSeries() {
      return brand_series;
    }


    /**
      * Sets the value of the 'brand_series' field.
      * @param value The value of 'brand_series'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setBrandSeries(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.brand_series = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'brand_series' field has been set.
      * @return True if the 'brand_series' field has been set, false otherwise.
      */
    public boolean hasBrandSeries() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'brand_series' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearBrandSeries() {
      brand_series = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'brand_word' field.
      * @return The value.
      */
    public java.lang.CharSequence getBrandWord() {
      return brand_word;
    }


    /**
      * Sets the value of the 'brand_word' field.
      * @param value The value of 'brand_word'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setBrandWord(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.brand_word = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'brand_word' field has been set.
      * @return True if the 'brand_word' field has been set, false otherwise.
      */
    public boolean hasBrandWord() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'brand_word' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearBrandWord() {
      brand_word = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'key_word' field.
      * @return The value.
      */
    public java.lang.CharSequence getKeyWord() {
      return key_word;
    }


    /**
      * Sets the value of the 'key_word' field.
      * @param value The value of 'key_word'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setKeyWord(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.key_word = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'key_word' field has been set.
      * @return True if the 'key_word' field has been set, false otherwise.
      */
    public boolean hasKeyWord() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'key_word' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearKeyWord() {
      key_word = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'ip' field.
      * @return The value.
      */
    public java.lang.CharSequence getIp() {
      return ip;
    }


    /**
      * Sets the value of the 'ip' field.
      * @param value The value of 'ip'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setIp(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.ip = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'ip' field has been set.
      * @return True if the 'ip' field has been set, false otherwise.
      */
    public boolean hasIp() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'ip' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearIp() {
      ip = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'imei' field.
      * @return The value.
      */
    public java.lang.CharSequence getImei() {
      return imei;
    }


    /**
      * Sets the value of the 'imei' field.
      * @param value The value of 'imei'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setImei(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.imei = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'imei' field has been set.
      * @return True if the 'imei' field has been set, false otherwise.
      */
    public boolean hasImei() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'imei' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearImei() {
      imei = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'oaid' field.
      * @return The value.
      */
    public java.lang.CharSequence getOaid() {
      return oaid;
    }


    /**
      * Sets the value of the 'oaid' field.
      * @param value The value of 'oaid'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setOaid(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.oaid = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'oaid' field has been set.
      * @return True if the 'oaid' field has been set, false otherwise.
      */
    public boolean hasOaid() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'oaid' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearOaid() {
      oaid = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'create_time' field.
      * @return The value.
      */
    public java.lang.Long getCreateTime() {
      return create_time;
    }


    /**
      * Sets the value of the 'create_time' field.
      * @param value The value of 'create_time'.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder setCreateTime(java.lang.Long value) {
      validate(fields()[12], value);
      this.create_time = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'create_time' field has been set.
      * @return True if the 'create_time' field has been set, false otherwise.
      */
    public boolean hasCreateTime() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'create_time' field.
      * @return This builder.
      */
    public com.ynthm.avro.cf88_trex.cf_app_startlog.Value.Builder clearCreateTime() {
      create_time = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Value build() {
      try {
        Value record = new Value();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.package_name = fieldSetFlags()[1] ? this.package_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.version = fieldSetFlags()[2] ? this.version : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.deviceType = fieldSetFlags()[3] ? this.deviceType : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.source = fieldSetFlags()[4] ? this.source : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.media = fieldSetFlags()[5] ? this.media : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.brand_series = fieldSetFlags()[6] ? this.brand_series : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.brand_word = fieldSetFlags()[7] ? this.brand_word : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.key_word = fieldSetFlags()[8] ? this.key_word : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.ip = fieldSetFlags()[9] ? this.ip : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.imei = fieldSetFlags()[10] ? this.imei : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.oaid = fieldSetFlags()[11] ? this.oaid : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.create_time = fieldSetFlags()[12] ? this.create_time : (java.lang.Long) defaultValue(fields()[12]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Value>
    WRITER$ = (org.apache.avro.io.DatumWriter<Value>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Value>
    READER$ = (org.apache.avro.io.DatumReader<Value>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    if (this.package_name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.package_name);
    }

    if (this.version == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.version);
    }

    if (this.deviceType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.deviceType);
    }

    if (this.source == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.source);
    }

    if (this.media == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.media);
    }

    if (this.brand_series == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.brand_series);
    }

    if (this.brand_word == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.brand_word);
    }

    if (this.key_word == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.key_word);
    }

    if (this.ip == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.ip);
    }

    if (this.imei == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.imei);
    }

    if (this.oaid == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.oaid);
    }

    if (this.create_time == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.create_time);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.package_name = null;
      } else {
        this.package_name = in.readString(this.package_name instanceof Utf8 ? (Utf8)this.package_name : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.version = null;
      } else {
        this.version = in.readString(this.version instanceof Utf8 ? (Utf8)this.version : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.deviceType = null;
      } else {
        this.deviceType = in.readString(this.deviceType instanceof Utf8 ? (Utf8)this.deviceType : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.source = null;
      } else {
        this.source = in.readString(this.source instanceof Utf8 ? (Utf8)this.source : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.media = null;
      } else {
        this.media = in.readString(this.media instanceof Utf8 ? (Utf8)this.media : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.brand_series = null;
      } else {
        this.brand_series = in.readString(this.brand_series instanceof Utf8 ? (Utf8)this.brand_series : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.brand_word = null;
      } else {
        this.brand_word = in.readString(this.brand_word instanceof Utf8 ? (Utf8)this.brand_word : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.key_word = null;
      } else {
        this.key_word = in.readString(this.key_word instanceof Utf8 ? (Utf8)this.key_word : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.ip = null;
      } else {
        this.ip = in.readString(this.ip instanceof Utf8 ? (Utf8)this.ip : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.imei = null;
      } else {
        this.imei = in.readString(this.imei instanceof Utf8 ? (Utf8)this.imei : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.oaid = null;
      } else {
        this.oaid = in.readString(this.oaid instanceof Utf8 ? (Utf8)this.oaid : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.create_time = null;
      } else {
        this.create_time = in.readLong();
      }

    } else {
      for (int i = 0; i < 13; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.package_name = null;
          } else {
            this.package_name = in.readString(this.package_name instanceof Utf8 ? (Utf8)this.package_name : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.version = null;
          } else {
            this.version = in.readString(this.version instanceof Utf8 ? (Utf8)this.version : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.deviceType = null;
          } else {
            this.deviceType = in.readString(this.deviceType instanceof Utf8 ? (Utf8)this.deviceType : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.source = null;
          } else {
            this.source = in.readString(this.source instanceof Utf8 ? (Utf8)this.source : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.media = null;
          } else {
            this.media = in.readString(this.media instanceof Utf8 ? (Utf8)this.media : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.brand_series = null;
          } else {
            this.brand_series = in.readString(this.brand_series instanceof Utf8 ? (Utf8)this.brand_series : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.brand_word = null;
          } else {
            this.brand_word = in.readString(this.brand_word instanceof Utf8 ? (Utf8)this.brand_word : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.key_word = null;
          } else {
            this.key_word = in.readString(this.key_word instanceof Utf8 ? (Utf8)this.key_word : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ip = null;
          } else {
            this.ip = in.readString(this.ip instanceof Utf8 ? (Utf8)this.ip : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.imei = null;
          } else {
            this.imei = in.readString(this.imei instanceof Utf8 ? (Utf8)this.imei : null);
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.oaid = null;
          } else {
            this.oaid = in.readString(this.oaid instanceof Utf8 ? (Utf8)this.oaid : null);
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.create_time = null;
          } else {
            this.create_time = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










