###
GET {{baseUrl}}/users/1
Accept: application/json

###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Ethan Wang",
  "age": 18,
  "birth": "2002-08-04",
  "amount": 20.8
}

###

PUT {{baseUrl}}/users
Content-Type: application/json

{
  "id": 1,
  "name": "Ethan Wang",
  "age": 27,
  "birth": "2001-08-04",
  "amount": 20.8
}

###

DELETE {{baseUrl}}/users/3
